"""add_traceability_columns

Revision ID: 0ef85ca01810
Revises: 5acaf4213581
Create Date: 2026-06-14 17:37:47.800332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef85ca01810'
down_revision = '5acaf4213581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_risk_predictions_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_predictions_trace_id'))
        batch_op.drop_column('trace_id')

    # ### end Alembic commands ###
