"""add ai model tracking tables

Revision ID: 36d720ea3b4a
Revises: f5237264e209
Create Date: 2026-06-14 16:52:34.236638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d720ea3b4a'
down_revision = 'f5237264e209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_importance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_training_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_info', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_version_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_risk_predictions_model_version', 'model_versions', ['model_version_id'], ['id'])
        batch_op.drop_column('model_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_version', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_risk_predictions_model_version', type_='foreignkey')
        batch_op.drop_column('model_version_id')

    op.drop_table('model_training_logs')
    op.drop_table('feature_importance')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
