"""add_intervention_recommendation_engine

Revision ID: 5acaf4213581
Revises: 28ddc9b60ebe
Create Date: 2026-06-14 17:24:52.174360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acaf4213581'
down_revision = '28ddc9b60ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('suggested_duration_days', sa.Integer(), nullable=True),
    sa.Column('responsible_role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('risk_prediction_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('supervisor_notes', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('predicted_effectiveness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_prediction_id'], ['risk_predictions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['intervention_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['intervention_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level_before', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('risk_level_after', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gpa_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gpa_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attendance_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attendance_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engagement_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engagement_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('effectiveness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_intervention_outcomes_completed_by', 'users', ['completed_by_id'], ['id'])

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_interventions_assigned_to', 'users', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key('fk_interventions_recommendation', 'intervention_recommendations', ['recommendation_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('recommendation_id')

    with op.batch_alter_table('intervention_outcomes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('effectiveness_score')
        batch_op.drop_column('engagement_after')
        batch_op.drop_column('engagement_before')
        batch_op.drop_column('attendance_after')
        batch_op.drop_column('attendance_before')
        batch_op.drop_column('gpa_after')
        batch_op.drop_column('gpa_before')
        batch_op.drop_column('risk_level_after')
        batch_op.drop_column('risk_level_before')

    op.drop_table('recommendation_evidence')
    op.drop_table('intervention_recommendations')
    op.drop_table('intervention_templates')
    # ### end Alembic commands ###
