"""add academic_years table and update semester

Revision ID: 5fe76ddd204f
Revises: 36d720ea3b4a
Create Date: 2026-06-14 16:55:03.195467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe76ddd204f'
down_revision = '36d720ea3b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('year_label', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key('fk_semesters_academic_year', 'academic_years', ['academic_year_id'], ['id'])
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('fk_semesters_academic_year', type_='foreignkey')
        batch_op.drop_column('academic_year_id')

    op.drop_table('academic_years')
    # ### end Alembic commands ###
