"""add_intervention_effectiveness

Revision ID: a3c537db8c0e
Revises: 0ef85ca01810
Create Date: 2026-06-14 17:50:53.168422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c537db8c0e'
down_revision = '0ef85ca01810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intervention_effectiveness',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('avg_effectiveness_score', sa.Float(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('risk_reduction_avg', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intervention_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention_effectiveness')
    # ### end Alembic commands ###
